name: "trigger ci / cd steps"
on:
  pull_request_target: # change this depending on which event you want to react
    types: [opened] 
jobs:
  cicdsteps:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
        with:
         deno-version: v1.x
      - run: | # uncomment the specific steps below which you want to be executed 
          deno --version
          deno run --allow-net https://deno.land/x/cicd/post-PR-checklist.ts ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.pull_request.number }}
          # deno run --allow-net https://deno.land/x/cicd/lint.ts
          # deno run --allow-net https://deno.land/x/cicd/security-scan.ts
          # deno run --allow-net https://deno.land/x/cicd/request-cla-signature.ts
          # deno run --allow-net https://deno.land/x/cicd/request-dco-signature.ts         
          # deno run --allow-net https://deno.land/x/cicd/publish-on-nest.land.ts          
          # deno run --allow-net https://deno.land/x/cicd/create-patch-release.ts                    
          # deno run --allow-net https://deno.land/x/cicd/create-minor-release.ts                    
          # deno run --allow-net https://deno.land/x/cicd/create-major-release.ts
          # deno run --allow-net https://deno.land/x/cicd/notify-via-telegram.ts
          # deno run --allow-net https://deno.land/x/cicd/notify-via-slack.ts
          # deno run --allow-net https://deno.land/x/cicd/notify-via-discord.ts

# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context


